// Mock data representing API response for waxing page
export const WaxingMockData = {
    pageContent: {
        title: "Waxing Services",
        description: `<p>For maximum benefit and complete hair removal, a minimum of quarter inch hair length is required.&nbsp;<br>We cannot perform waxing services on Guests who are taking (currently or within the last year) Accutane, Retinol A, or any medication that increases skin sensitivity. Waxing is also not suitable if you are sunburnt&nbsp;or have received a recent Laser treatment or Chemical peel.</p>
            <figure class="wp-block-table price-table"><table><tbody><tr><td><strong>Brow Shape</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td><td>$25</td></tr><tr><td><strong>Lip &amp; Brow&nbsp; &nbsp;</strong>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td><td>$45</td></tr><tr><td><strong>Lip or Chin</strong></td><td>$20</td></tr><tr><td><strong>Lip &amp; Chin&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></td><td>$40</td></tr><tr><td><strong>Full Face&nbsp; &nbsp; &nbsp;&nbsp;</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td><td>$60</td></tr><tr><td><strong>Half Arm&nbsp; &nbsp;&nbsp;</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td><td>$35</td></tr><tr><td><strong>Full Arm</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</td><td>$50</td></tr><tr><td><strong>Underarm</strong>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td><td>$25</td></tr><tr><td><strong>Chest</strong></td><td>$35</td></tr><tr><td><strong>Back Half/Full</strong></td><td>$40/60</td></tr><tr><td><strong>Lower Leg</strong>&nbsp;</td><td>$45</td></tr><tr><td><strong>Upper Leg</strong></td><td>$50</td></tr><tr><td><strong>Full Leg</strong></td><td>$75</td></tr><tr><td><strong>Half Leg &amp; Bikini Line</strong></td><td>$70</td></tr><tr><td><strong>Bikini (Basic Line)&nbsp;</strong></td><td>$30</td></tr></tbody></table></figure>
            <p></p><p></p>`,
    },
};

export default WaxingMockData;